/**
 * Lightning Continuation Helper test class.
 * <p /><p />
 * @author Raymundo Rodriguez
 */
@isTest(seeAllData = false)
private class LightningContinuationHelperTest_CF {

    /**
     * Method to test the initialization of the class.
     */
    @isTest
    static void testConstructor() {
        LightningContinuationHelperController_CF objController = new LightningContinuationHelperController_CF();
    }
}