/**
 * Test class for Static_VariablesClass_CF.
 * <p /><p />
 * @author Alberto Gomez.
 */
@isTest
public class StaticVariablesTest_CF {
    /**
     * Initialize constants for Custom Framework.
     */
    static testmethod void initializeVariables() {

        //Custom framework variables.
        System.assertNotEquals('', StaticVariablesClass_CF.CUSTOM_FRAMEWORK_EXAMPLE_1_NAME, 'Variable is not returning any value');
        System.assertNotEquals('', StaticVariablesClass_CF.CUSTOM_FRAMEWORK_EXAMPLE_1_POSITION, 'Variable is not returning any value');
        System.assertNotEquals('', StaticVariablesClass_CF.CUSTOM_FRAMEWORK_EXAMPLE_1_OFFICE, 'Variable is not returning any value');
        System.assertNotEquals('', StaticVariablesClass_CF.CUSTOM_FRAMEWORK_EXAMPLE_1_SALARY, 'Variable is not returning any value');
        System.assertNotEquals('', StaticVariablesClass_CF.CUSTOM_FRAMEWORK_EXAMPLE_2_NAME, 'Variable is not returning any value');
        System.assertNotEquals('', StaticVariablesClass_CF.CUSTOM_FRAMEWORK_EXAMPLE_2_POSITION, 'Variable is not returning any value');
        System.assertNotEquals('', StaticVariablesClass_CF.CUSTOM_FRAMEWORK_EXAMPLE_2_OFFICE, 'Variable is not returning any value');
        System.assertNotEquals('', StaticVariablesClass_CF.CUSTOM_FRAMEWORK_EXAMPLE_2_SALARY, 'Variable is not returning any value');
        System.assertNotEquals('', StaticVariablesClass_CF.CUSTOM_FRAMEWORK_EXAMPLE_3_NAME, 'Variable is not returning any value');
        System.assertNotEquals('', StaticVariablesClass_CF.CUSTOM_FRAMEWORK_EXAMPLE_3_POSITION, 'Variable is not returning any value');
        System.assertNotEquals('', StaticVariablesClass_CF.CUSTOM_FRAMEWORK_EXAMPLE_3_OFFICE, 'Variable is not returning any value');
        System.assertNotEquals('', StaticVariablesClass_CF.CUSTOM_FRAMEWORK_EXAMPLE_3_SALARY, 'Variable is not returning any value');
        System.assertNotEquals('', StaticVariablesClass_CF.CUSTOM_FRAMEWORK_EXAMPLE_4_ALPHA_CODE, 'Variable is not returning any value');
        System.assertNotEquals('', StaticVariablesClass_CF.CUSTOM_FRAMEWORK_EXAMPLE_4_POSITION, 'Variable is not returning any value');
        System.assertNotEquals('', StaticVariablesClass_CF.CUSTOM_FRAMEWORK_EXAMPLE_5_ALPHA_CODE, 'Variable is not returning any value');
        System.assertNotEquals('', StaticVariablesClass_CF.CUSTOM_FRAMEWORK_EXAMPLE_5_POSITION, 'Variable is not returning any value');
        System.assertNotEquals('', StaticVariablesClass_CF.CUSTOM_FRAMEWORK_EXAMPLE_6_ALPHA_CODE, 'Variable is not returning any value');
        System.assertNotEquals('', StaticVariablesClass_CF.CUSTOM_FRAMEWORK_EXAMPLE_6_POSITION, 'Variable is not returning any value');
        System.assertNotEquals('', StaticVariablesClass_CF.CUSTOM_FRAMEWORK_EXAMPLE_7_ALPHA_CODE, 'Variable is not returning any value');
        System.assertNotEquals('', StaticVariablesClass_CF.CUSTOM_FRAMEWORK_EXAMPLE_7_POSITION, 'Variable is not returning any value');
        System.assertNotEquals('', StaticVariablesClass_CF.CUSTOM_FRAMEWORK_EXAMPLE_8_ALPHA_CODE, 'Variable is not returning any value');
        System.assertNotEquals('', StaticVariablesClass_CF.CUSTOM_FRAMEWORK_EXAMPLE_8_POSITION, 'Variable is not returning any value');
        System.assertNotEquals('', StaticVariablesClass_CF.CUSTOM_FRAMEWORK_EXAMPLE_9_ALPHA_CODE, 'Variable is not returning any value');
        System.assertNotEquals('', StaticVariablesClass_CF.CUSTOM_FRAMEWORK_EXAMPLE_9_POSITION, 'Variable is not returning any value');
        System.assertNotEquals('', StaticVariablesClass_CF.CUSTOM_FRAMEWORK_EXAMPLE_10_ALPHA_CODE, 'Variable is not returning any value');
        System.assertNotEquals('', StaticVariablesClass_CF.CUSTOM_FRAMEWORK_EXAMPLE_10_POSITION, 'Variable is not returning any value');
        System.assertNotEquals('', StaticVariablesClass_CF.CUSTOM_FRAMEWORK_EXAMPLE_11_ALPHA_CODE, 'Variable is not returning any value');
        System.assertNotEquals('', StaticVariablesClass_CF.CUSTOM_FRAMEWORK_EXAMPLE_11_POSITION, 'Variable is not returning any value');
        System.assertNotEquals('', StaticVariablesClass_CF.CUSTOM_FRAMEWORK_EXAMPLE_12_NAME, 'Variable is not returning any value');
        System.assertNotEquals('', StaticVariablesClass_CF.CUSTOM_FRAMEWORK_EXAMPLE_12_POSITION, 'Variable is not returning any value');
        System.assertNotEquals('', StaticVariablesClass_CF.CUSTOM_FRAMEWORK_EXAMPLE_12_OFFICE, 'Variable is not returning any value');
        System.assertNotEquals('', StaticVariablesClass_CF.CUSTOM_FRAMEWORK_EXAMPLE_12_SALARY, 'Variable is not returning any value');
        System.assertNotEquals('', StaticVariablesClass_CF.CUSTOM_FRAMEWORK_EXAMPLE_13_NAME, 'Variable is not returning any value');
        System.assertNotEquals('', StaticVariablesClass_CF.CUSTOM_FRAMEWORK_EXAMPLE_13_POSITION, 'Variable is not returning any value');
        System.assertNotEquals('', StaticVariablesClass_CF.CUSTOM_FRAMEWORK_EXAMPLE_13_OFFICE, 'Variable is not returning any value');
        System.assertNotEquals('', StaticVariablesClass_CF.CUSTOM_FRAMEWORK_EXAMPLE_13_SALARY, 'Variable is not returning any value');
        System.assertNotEquals('', StaticVariablesClass_CF.CUSTOM_FRAMEWORK_FATAL_MESSAGE, 'Variable is not returning any value');
        System.assertNotEquals('', StaticVariablesClass_CF.CUSTOM_FRAMEWORK_SUCCESS_MESSAGE, 'Variable is not returning any value');
        System.assertNotEquals('', StaticVariablesClass_CF.CUSTOM_FRAMEWORK_MEMBER_ID, 'Variable is not returning any value');
        System.assertNotEquals('', StaticVariablesClass_CF.CUSTOM_FRAMEWORK_ACCOUNT, 'Variable is not returning any value');
        System.assertNotEquals('', StaticVariablesClass_CF.CUSTOM_FRAMEWORK_BILING_CITY, 'Variable is not returning any value');
        System.assertNotEquals('', StaticVariablesClass_CF.CUSTOM_FRAMEWORK_GRAPHS, 'Variable is not returning any value');
        System.assertNotEquals('', StaticVariablesClass_CF.CUSTOM_FRAMEWORK_ACCOUNT_RECORD_TYPE, 'Variable is not returning any value');
        System.assertNotEquals('', StaticVariablesClass_CF.CUSTOM_FRAMEWORK_LIGHTNING_URL_HTTPS, 'Variable is not returning any value');
        System.assertNotEquals('', StaticVariablesClass_CF.CUSTOM_FRAMEWORK_LIGHTNING_URL_FORCE_ONE_APP, 'Variable is not returning any value');
        System.assertNotEquals('', StaticVariablesClass_CF.CUSTOM_FRAMEWORK_LIGHTNING_URL_C, 'Variable is not returning any value');
        System.assertNotEquals('', StaticVariablesClass_CF.CUSTOM_FRAMEWORK_LIGHTNING_URL_HTTPS_C_PREFIX, 'Variable is not returning any value');
        System.assertNotEquals('', StaticVariablesClass_CF.CUSTOM_FRAMEWORK_LIGHTNING_URL_VISUAL_FORCE, 'Variable is not returning any value');
        System.assertEquals('', StaticVariablesClass_CF.CUSTOM_FRAMEWORK_BLANK, 'Variable is not returning any value');
    }
}